<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.0.1-prealpha</Version>
		<PackageVersion>$(Version)</PackageVersion>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/VladUl287/WebSoket.Otp</PackageProjectUrl>
		<RepositoryUrl>https://github.com/VladUl287/WebSoket.Otp</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebSocket.Otp.Abstractions\WebSockets.Otp.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="StackExchange.Redis" Version="3.2.0" />
	</ItemGroup>

</Project>
